// <auto-generated />
using System;
using Ecommerce.Service.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Service.ProductAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241106014744_AddSeed")]
    partial class AddSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Converse"
                        });
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Walking"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Training & Gym"
                        });
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 1,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/1.png"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 1,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/2.png"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 1,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/3.png"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 1,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/4.png"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 2,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/5.png"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 2,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/6.png"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 2,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/7.png"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 2,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/8.png"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/9.png"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/10.png"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/11.png"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 1,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/12.png"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/13.png"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/14.png"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 3,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/15.png"
                        },
                        new
                        {
                            Id = 16,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 4,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/16.png"
                        },
                        new
                        {
                            Id = 17,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 4,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 4,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/1.jpg"
                        },
                        new
                        {
                            Id = 19,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 5,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/2.jpg"
                        },
                        new
                        {
                            Id = 20,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 5,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/3.jpg"
                        },
                        new
                        {
                            Id = 21,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 5,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/4.jpg"
                        },
                        new
                        {
                            Id = 22,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 5,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/5.jpg"
                        },
                        new
                        {
                            Id = 23,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 6,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/6.jpg"
                        },
                        new
                        {
                            Id = 24,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 6,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/7.jpg"
                        },
                        new
                        {
                            Id = 25,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 6,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/8.jpg"
                        },
                        new
                        {
                            Id = 26,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 6,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/9.jpg"
                        },
                        new
                        {
                            Id = 27,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 7,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/10.jpg"
                        },
                        new
                        {
                            Id = 28,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 7,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/11.jpg"
                        },
                        new
                        {
                            Id = 29,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 7,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 7,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/12.jpg"
                        },
                        new
                        {
                            Id = 31,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 8,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/13.jpg"
                        },
                        new
                        {
                            Id = 32,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 8,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/14.jpg"
                        },
                        new
                        {
                            Id = 33,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 8,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/15.jpg"
                        },
                        new
                        {
                            Id = 34,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 8,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/16.jpg"
                        },
                        new
                        {
                            Id = 35,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 9,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/17.jpg"
                        },
                        new
                        {
                            Id = 36,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 9,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/18.jpg"
                        },
                        new
                        {
                            Id = 37,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 9,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/19.jpg"
                        },
                        new
                        {
                            Id = 38,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 10,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/20.jpg"
                        },
                        new
                        {
                            Id = 39,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 11,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/21.jpg"
                        },
                        new
                        {
                            Id = 40,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 12,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/22.jpg"
                        },
                        new
                        {
                            Id = 41,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 12,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/23.jpg"
                        },
                        new
                        {
                            Id = 42,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 12,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/24.jpg"
                        },
                        new
                        {
                            Id = 43,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 12,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/25.jpg"
                        },
                        new
                        {
                            Id = 44,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 13,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/26.jpg"
                        },
                        new
                        {
                            Id = 45,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 13,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/27.jpg"
                        },
                        new
                        {
                            Id = 46,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 13,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/28.jpg"
                        },
                        new
                        {
                            Id = 47,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 13,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/29.jpg"
                        },
                        new
                        {
                            Id = 48,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/30.jpg"
                        },
                        new
                        {
                            Id = 49,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/31.jpg"
                        },
                        new
                        {
                            Id = 50,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/32.jpg"
                        },
                        new
                        {
                            Id = 51,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/33.jpg"
                        },
                        new
                        {
                            Id = 52,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/33.jpg"
                        },
                        new
                        {
                            Id = 53,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 14,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/34.jpg"
                        },
                        new
                        {
                            Id = 54,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 15,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/35.jpg"
                        },
                        new
                        {
                            Id = 55,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 15,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/36.jpg"
                        },
                        new
                        {
                            Id = 56,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 15,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/37.jpg"
                        },
                        new
                        {
                            Id = 57,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 16,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/38.jpg"
                        },
                        new
                        {
                            Id = 58,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 16,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/39.jpg"
                        },
                        new
                        {
                            Id = 59,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 16,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/40.jpg"
                        },
                        new
                        {
                            Id = 60,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 17,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/39.jpg"
                        },
                        new
                        {
                            Id = 61,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 17,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/40.jpg"
                        },
                        new
                        {
                            Id = 62,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 17,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/41.jpg"
                        },
                        new
                        {
                            Id = 63,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 17,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/42.jpg"
                        },
                        new
                        {
                            Id = 64,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 17,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/43.jpg"
                        },
                        new
                        {
                            Id = 65,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 18,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/44.jpg"
                        },
                        new
                        {
                            Id = 66,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 18,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/45.jpg"
                        },
                        new
                        {
                            Id = 68,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 19,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/46.jpg"
                        },
                        new
                        {
                            Id = 69,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 19,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/47.jpg"
                        },
                        new
                        {
                            Id = 70,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 19,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/48.jpg"
                        },
                        new
                        {
                            Id = 71,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 19,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/49.jpg"
                        },
                        new
                        {
                            Id = 72,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 20,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/50.jpg"
                        },
                        new
                        {
                            Id = 73,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 20,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/51.jpg"
                        },
                        new
                        {
                            Id = 74,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 20,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/52.jpg"
                        },
                        new
                        {
                            Id = 75,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 20,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/53.jpg"
                        },
                        new
                        {
                            Id = 76,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 20,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/54.jpg"
                        },
                        new
                        {
                            Id = 77,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/55.jpg"
                        },
                        new
                        {
                            Id = 78,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/56.jpg"
                        },
                        new
                        {
                            Id = 79,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/57.jpg"
                        },
                        new
                        {
                            Id = 80,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/58.jpg"
                        },
                        new
                        {
                            Id = 81,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/59.jpg"
                        },
                        new
                        {
                            Id = 82,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsMain = false,
                            ProductId = 21,
                            PublicId = "admin",
                            Url = "https://localhost:7000/ProductImages/60.jpg"
                        });
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("PriceBeforeDiscount")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("Sold")
                        .HasColumnType("int");

                    b.Property<int?>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Nike Air Force 1 '07",
                            Price = 150.0,
                            PriceBeforeDiscount = 200.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 2000,
                            View = 10000
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">Created for the hardwood but taken to the streets, this '80s basketball icon returns with classic details and throwback hoops flair. The synthetic leather overlays help the Nike Dunk channel vintage style while its padded, low-cut collar lets you take your game anywhere—in comfort.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->Summit White/Baroque Brown/Phantom/Khaki</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->HF4292-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Indonesia</li></ul></div>",
                            Name = "Nike Dunk Low",
                            Price = 180.0,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 30,
                            Rating = 5.0,
                            Sold = 3200,
                            View = 2800
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">With maximum cushioning to support every mile, the Invincible 3 gives you our highest level of comfort underfoot to help you stay on your feet today, tomorrow and beyond. Engineered to the exact specifications of championship athletes, ultra-responsive and lightweight ZoomX foam helps keep you on the run. It can help propel you down your preferred path and come back for your next run feeling ready and reinvigorated.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->Multi-Colour/Multi-Colour</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->HJ6653-900</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Nike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-ColourNike Invincible 3 Blueprint Men's Road Running Shoes - Multi-Colour/Multi-Colour\r\nNike Invincible 3 Blueprint\r\nMen's Road Running Shoes",
                            Price = 186.0,
                            PriceBeforeDiscount = 220.0,
                            Quantity = 50,
                            Rating = 3.3999999999999999,
                            Sold = 1400,
                            View = 1000
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">Inspired by the original that debuted in 1985, the Air Jordan 1 Low offers a clean, classic look that's familiar yet always fresh. With an iconic design that pairs perfectly with any 'fit, these kicks ensure you'll always be on point.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->553558-132</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Air Jordan 1 Low\r\nMen's Shoes",
                            Price = 190.0,
                            Quantity = 100,
                            Rating = 2.7000000000000002,
                            Sold = 200,
                            View = 32000
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "<div class=\"text-content___13aRm\"><h3 class=\"subtitle___9ljbp\">An iconic design with contemporary comfort.</h3><p class=\"gl-vspace\">First released in 1972 to equip athletes for the Summer event, the adidas SL 72 OG shoes have a lightweight build that revolutionised running. Today, the breathable nylon upper, suede overlays and leather accents bring retro-inspired style to your active life. An Ecotex tongue adds texture, and the EVA midsole keeps you comfortable on the go. The classic low-profile cut and rubber outsole deliver the final touches.</p></div>",
                            Name = "SL 72 OG Shoes",
                            Price = 150.0,
                            PriceBeforeDiscount = 160.0,
                            Quantity = 32,
                            Rating = 4.2999999999999998,
                            Sold = 3352,
                            View = 4000
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "<div class=\"text-content___13aRm\"><h3 class=\"subtitle___9ljbp\">Sport-inspired shoes with a retro look, modern comfort and a rich past.</h3><p class=\"gl-vspace\">Long before the adidas Samba shoes took to the streets, they left their mark on the indoor football pitch. Their smooth leather upper, nubuck toe cap and reinforced rubber sole were designed with agility and control in mind. Though times have changed, their essence remains. Today, they carry on the legacy as an iconic street style, ready for whatever your day brings. Moulded into their design is decades of history, keeping the spirit of the Trefoil alive.</p></div>",
                            Name = "Samba OG Shoes",
                            Price = 180.0,
                            Quantity = 50,
                            Rating = 3.6000000000000001,
                            Sold = 2200,
                            View = 8289
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 3,
                            Description = "<div class=\"text-content___13aRm\"><h3 class=\"subtitle___9ljbp\">adidas Samba shoes in collaboration with Wales Bonner.</h3><p class=\"gl-vspace\">The Fall/Winter 2024 collection from adidas and Wales Bonner merges tradition with modernity in a celebration of hip hop movement and romanticism. Music and creative vibrancy are threaded into the collection through the textures, shapes and colours across the pieces.\r\n\r\nWith one of adidas' most iconic silhouette as a canvas, the Wales Bonner MN Samba Shoes channel a collegiate aesthetic through different materials and contrasting tones. The split is done with yellow suede on the front half, and a navy croc-embossed pattern towards the back. Everything is detailed with intricate deco-stitching.</p></div>",
                            Name = "Wales Bonner MN Samba Shoes",
                            Price = 320.0,
                            PriceBeforeDiscount = 400.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 1500,
                            View = 10000
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "<div class=\"text-content___13aRm\"><h3 class=\"subtitle___9ljbp\">Entirely new (but archive-inspired) lifestyle shoes made with Dingyun Zhang.</h3><p class=\"gl-vspace\">The silhouette of the adidas Kouza shoes has clearly been put under Dingyun Zhang's disruptive lens — and what's seen is a progressive blend of both product and art. Taking inspiration from sci-fi, otherworldly creations and a true love of street culture, the Chinese designer brings to life a completely new running-inspired shoe that nods to the adidas archives. The ultra-lightweight, chunky silhouette provides durability and breathability, and features a incredibly comfortable Lightstrike midsole. A mix of materials form the upper, creating a play between textures and layers.</p></div>",
                            Name = "Dingyun Zhang Kouza",
                            Price = 230.0,
                            PriceBeforeDiscount = 450.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 2670,
                            View = 10000
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "<div class=\"col-12 value content short-description px-0 pb-3\" id=\"collapsible-description-1\">\r\n                    If we only made one running shoe, it would be the Fresh Foam X 1080. The unique combination of reliable comfort and high performance offers versatility that spans from every day to race day. The Fresh Foam X midsole cushioning is built for smooth transitions from landing to push-off, while a soft, premium upper provides support and breathability.<br><br>Updates to the v14 include a new, triple jacquard mesh upper with increased breathability in key areas, an updated outsole for a propulsive feeling, and additional rubber in high wear areas for added durability.\r\n                </div>",
                            Name = "Fresh Foam X 1080 v14",
                            Price = 270.0,
                            PriceBeforeDiscount = 320.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 1450,
                            View = 10000
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            CategoryId = 3,
                            Description = "<div class=\"accordion-content\" part=\"accordion-content\" id=\"accordion-f827a\">\r\n                <div>\r\n                    <slot></slot>\r\n                </div>\r\n            </div>",
                            Name = "FuelCell MD500 v9",
                            Price = 120.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 220,
                            View = 10000
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CategoryId = 3,
                            Description = "<div class=\"col-12 value content short-description px-0 pb-3\" id=\"collapsible-description-1\">\r\n                    Your new favorite training partner. This running shoe features an innovative midsole design with ground contact EVA outsole for a lightweight, propulsive, and fast underfoot feel to take you seamlessly from training to race day.\r\n                </div>",
                            Name = "Fresh Foam X Balos",
                            Price = 295.0,
                            PriceBeforeDiscount = 340.0,
                            Quantity = 10,
                            Rating = 4.0,
                            View = 1996
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CategoryId = 4,
                            Description = "<div class=\"col-12 value content short-description px-0 pb-3\" id=\"collapsible-description-1\">\r\n                    Whatever your preferred running routine looks like, there’s no shoe that handles it quite like the 880. The Fresh Foam X 880v14 is an evolution in everyday reliability, featuring superior underfoot cushioning and a structured, supportive upper.\r\n                </div>",
                            Name = "Fresh Foam X 880v14",
                            Price = 195.0,
                            PriceBeforeDiscount = 240.0,
                            Quantity = 10,
                            Rating = 4.0,
                            View = 10000
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "<div class=\"product attribute description\" id=\"product-description\"> <div class=\"value\"><h2>HIGH FASHION</h2>\r\n<p>Turn every hallway into your own personal runway with extra-high Chucks. Angular lines and crocodile-inspired details bring a luxe look with just enough edge.</p>\r\n<h3>Details</h3>\r\n<ul>\r\n<li>Croc-embossed leather brings a luxe look and feel</li>\r\n<li>OrthoLite cushioning helps provide optimal comfort</li>\r\n<li>Tonal laces and gold eyelets elevate your style</li>\r\n<li>Angular lines and eyelets remix Chuck Taylor DNA</li>\r\n<li>Iconic Chuck Taylor ankle patch and vintage All Star license plate</li>\r\n</ul>\r\n<h3>Chuck 70 Origins</h3>\r\n<p>By 1970, the Chuck had evolved to become the pinnacle of function and utility for sport, and was considered the best basketball sneaker ever. The Chuck 70 is built off of the original 1970s design, with premium materials and an extraordinary attention to detail. A shoe so rooted in tradition that it has its own instant history. That's the Chuck 70. It's not a shoe. It's the shoe.</p></div> <div><a href=\"#\" class=\"back-to-top _hide-for-tablet -scroll -down\">Back to top</a></div> </div>",
                            Name = "Unisex Converse Chuck 70 De Luxe Squared Leather High Top Bloodstone",
                            Price = 200.0,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 6,
                            Rating = 4.0,
                            Sold = 1996,
                            View = 18
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "<div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\" data-pb-style=\"V6MM40P\"><div>\r\n<h2>FALL FAVOURITE.</h2>\r\n</div>\r\n<p id=\"VW4NQSG\">Just in time for cooler weather, your favourite Chucks get a fresh look for the season. Fall-ready canvas in trending colors help you add standout style to your rotation. On those shorter days, why not add some colour to your look?</p>\r\n<div>\r\n<h3>Details</h3>\r\n<ul>\r\n<li>High top with canvas upper</li>\r\n<li>OrthoLite cushioning for all-day comfort</li>\r\n<li>On-trend colour palette</li>\r\n<li>Durable polyester laces</li>\r\n<li>Fused All Star patch</li>\r\n</ul>\r\n</div>\r\n<div>\r\n<h3>Chuck Taylor All Star Origins</h3>\r\n</div>\r\n<p>Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor. But over the decades, something incredible happened: The sneaker, with its timeless silhouette and unmistakable ankle patch, was organically adopted by rebels, artists, musicians, dreamers, thinkers and originals.</p></div>",
                            Name = "Unisex Converse Run Star Trainer Low Top Bloodstone",
                            Price = 140.0,
                            PriceBeforeDiscount = 210.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 2000,
                            View = 10000
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CategoryId = 3,
                            Description = "<div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"624598B54085D\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\" data-pb-style=\"624598B540868\"><div>\r\n<h2 class=\"pdp-tab__title text-align--sm-center\">EXPRESS YOURSELF WITH COLOUR.</h2>\r\n</div>\r\n<p id=\"VW4NQSG\">The laidback legend is back in fresh colours. Ready for dressing up or down, these classic canvas Chucks are an everyday wardrobe staple. Plus, we’ve softened up the lining, stitching and seams for maximum comfort all day, every day.</p>\r\n<div>\r\n<h3>Details</h3>\r\n<ul>\r\n<li class=\"pdp-tab__list-item\">Canvas high top sneakers.</li>\r\n<li class=\"pdp-tab__list-item\">OrthoLite insole for cushioning.</li>\r\n<li class=\"pdp-tab__list-item\">New hues bring a pop of colour to any outfit.</li>\r\n<li class=\"pdp-tab__list-item\">Classic woven tongue label and license plate.</li>\r\n<li class=\"pdp-tab__list-item\">Iconic Chuck Taylor ankle patch.</li>\r\n</ul>\r\n</div>\r\n<div>\r\n<h3>Chuck Taylor All Star Origins</h3>\r\n</div>\r\n<p>Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor. But over the decades, something incredible happened: The sneaker, with its timeless silhouette and unmistakable ankle patch, was organically adopted by rebels, artists, musicians, dreamers, thinkers and originals.</p></div></div></div>",
                            Name = "Unisex Converse Chuck Taylor All Star Seasonal Colour High Top Snorkel Blue",
                            Price = 150.0,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 2012,
                            View = 10000
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            CategoryId = 4,
                            Description = "<div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\" data-pb-style=\"PLSW2C1\"><div>\r\n<h2>REMASTERED CLASSIC</h2>\r\n</div>\r\n<p>Leather Chucks. They go with your suit and tie just as much as your sweats and tee. They’re durable and easier to clean—so feel free to wear them, like, all the time. And they’re built like the original, so your Chucks collection stays most iconic. Are you obsessed yet?</p>\r\n<div>\r\n<h3>Details</h3>\r\n<ul>\r\n<li>Luxe, full-grain leather upper, with that classic Chucks look</li>\r\n<li>OrthoLite cushioning helps to provide optimal comfort</li>\r\n<li>Iconic All Star tongue label and license plate</li>\r\n<li>Medial eyelets enhance airflow</li>\r\n</ul>\r\n</div>\r\n<div>\r\n<h3>Chuck Taylor All Star Origins</h3>\r\n</div>\r\n<p>Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor. But over the decades, something incredible happened: The sneaker, with its timeless silhouette and unmistakable ankle patch, was organically adopted by rebels, artists, musicians, dreamers, thinkers and originals.</p></div>",
                            Name = "Unisex Converse Chuck Taylor All Star Leather Low Top White\r\n",
                            Price = 160.0,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 20300,
                            View = 10000
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Nike Air Max 95",
                            Price = 380.0,
                            PriceBeforeDiscount = 390.0,
                            Quantity = 10,
                            Rating = 4.0,
                            Sold = 11212,
                            View = 10000
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Jumpman MVP",
                            Price = 161.99000000000001,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 10,
                            Rating = 2.6000000000000001,
                            Sold = 12012,
                            View = 2000
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            CategoryId = 4,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Nike Invincible 3 Blueprint Men's Road Running Shoes",
                            Price = 180.0,
                            PriceBeforeDiscount = 230.0,
                            Quantity = 10,
                            Rating = 2.5,
                            Sold = 152012,
                            View = 6300
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Air Jordan 1 Low",
                            Price = 190.0,
                            PriceBeforeDiscount = 330.0,
                            Quantity = 10,
                            Rating = 4.7999999999999998,
                            Sold = 4012,
                            View = 1000
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "<div id=\"product-description-container\" data-testid=\"product-description-container\" class=\"pt7-sm\"><p class=\"nds-text css-pxxozx e1yhcai00 text-align-start appearance-body1 color-primary weight-regular\" data-testid=\"product-description\">The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colours and the perfect amount of flash to make you shine.</p><br><ul class=\"css-1vql4bw eru6lik0 nds-list\" style=\"text-align:left\"><li data-testid=\"product-description-color-description\">Colour Shown:<!-- --> <!-- -->White/Black</li><li data-testid=\"product-description-style-color\">Style:<!-- --> <!-- -->CT2302-100</li><li data-testid=\"product-description-country-of-origin\">Country/Region of Origin: Vietnam</li></ul></div>",
                            Name = "Nike V2K Run",
                            Price = 180.0,
                            PriceBeforeDiscount = 250.0,
                            Quantity = 10,
                            Rating = 5.0,
                            Sold = 25512,
                            View = 34000
                        });
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Photo", b =>
                {
                    b.HasOne("Ecommerce.Service.ProductAPI.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Service.ProductAPI.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("Ecommerce.Service.ProductAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Service.ProductAPI.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
